# install necessary libraries
p <- c("optparse")
usePackage <- function(p) {
	if (!is.element(p, installed.packages()[,1]))
		install.packages(p, dep=TRUE, repos="http://cran.us.r-project.org/")
	suppressWarnings(suppressMessages(invisible(require(p, character.only=TRUE))))
}
invisible(lapply(p, usePackage))

## clean R environment
rm(list = ls())

## parsing arguments
args <- commandArgs(trailingOnly=TRUE)

# make option list and parse command line
option_list <- list(
	make_option(c("-i", "--table_file"), type="character", help="Input the species abundance file generated by 2bRAD-M [Required]"),
	#make_option(c("-m", "--meta"), type="character", help="Input the metadata file [Required]"),
	make_option(c("-p", "--min_presence_percentage"), type = "numeric", default=0.8, help = "Input the minimum percentage of samples within a group where a species must be present to be considered significant [default %default]"), 
	make_option(c("-t", "--threshold"), type="numeric", default=0.01, help="The minimum abundance value a species must have in a sample to be considered present [default %default]"),
	make_option(c("-o", "--out_file"), type="character", default='species_list.txt', help="Output file [default %default]")
)
opts <- parse_args(OptionParser(option_list=option_list), args=args)

# paramenter checking
if(is.null(opts$table_file)) stop('Please input a feature table with species abundance')
#if(is.null(opts$metadata)) stop('Please input a metadata file')

# load data
abd_file <- opts$table_file
#meta_file <- opts$meta
min_presence_percentage <- opts$min_presence_percentage
min_abundance <- opts$threshold
outfile <- opts$out_file

abd_2bRAD <- read.table(abd_file, sep = "\t", header = T, comment.char = "")

rownames(abd_2bRAD) <- abd_2bRAD$Species
abd_2bRAD <- abd_2bRAD[8:ncol(abd_2bRAD)]

#meta <- read.table(meta_file, sep = "\t", header = T, row.names = T, col.names = NA)
#if(! identical(rownames(abd_2bRAD), rownames(meta))) stop('Please ensure consistency between the row names (sample names) of the species abundance table and those of the metadata.')

abd_2bRAD[abd_2bRAD < min_abundance] <- 0
non_zero_rows <- abd_2bRAD[!apply(abd_2bRAD == 0, 1, any), ]

filtered_abd_2bRAD <- subset(abd_2bRAD, rownames(abd_2bRAD) %in% rownames(non_zero_rows))

filtered_species_list <- rownames(filtered_abd_2bRAD)
write.table(filtered_species_list, outfile, sep = "\t", quote = F, row.names = F, col.names = F)
